# Generated by Django 4.2.9 on 2024-02-02 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='userId',
        ),
    ]
